import { IDataObject, IExecuteFunctions } from 'n8n-workflow';
import { geminiApiRequest } from '../../../../utils/apiClient';
import { FileSearchStore } from '../../../../utils/types';
import { validateDisplayName } from '../../../../utils/validators';

/**
 * Creates a new Gemini File Search Store
 *
 * Creates a container for storing and searching documents using the Gemini File Search API.
 * The store name is automatically generated by the API.
 *
 * @param this - n8n execution context
 * @param index - Item index in the workflow execution
 * @returns Promise resolving to the created FileSearchStore with auto-generated name
 * @throws {NodeOperationError} When displayName exceeds 512 characters
 * @throws {NodeApiError} When API request fails
 *
 * @example
 * ```typescript
 * // Create store with display name
 * const store = await create.call(this, 0);
 * console.log(store.name); // 'fileSearchStores/auto-generated-id'
 * console.log(store.displayName); // 'My Document Store'
 * ```
 */
export async function create(this: IExecuteFunctions, index: number): Promise<FileSearchStore> {
  const displayName = this.getNodeParameter('displayName', index) as string;

  if (displayName) {
    validateDisplayName.call(this, displayName);
  }

  const body: IDataObject = {};
  if (displayName) {
    body.displayName = displayName;
  }

  // API client returns 'any', but we know the endpoint returns a FileSearchStore
  return geminiApiRequest.call(this, 'POST', '/fileSearchStores', body) as Promise<FileSearchStore>;
}
